apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-sleep
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/{username}/hello-sleep
        env:
        - name: TARGET
          value: "Go Sample v1"
